"""empty message

Revision ID: 1a1c8e92c16c
Revises: 2dda52c85a67
Create Date: 2026-07-03 22:33:04.504849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1c8e92c16c'
down_revision = '2dda52c85a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=120), nullable=False),
    sa.Column('parameter', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start', sa.String(length=8), nullable=False),
    sa.Column('end', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('event', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    # ### end Alembic commands ###
