"""Initial migration

Revision ID: e850da160e36
Revises: 
Create Date: 2026-07-09 16:50:49.093266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e850da160e36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=120), nullable=False),
    sa.Column('parameter', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start', sa.String(length=8), nullable=False),
    sa.Column('end', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('event', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meteorological',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freak', sa.String(length=120), nullable=False),
    sa.Column('cat', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freak_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['freak_id'], ['meteorological.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freak_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('work_recommendation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['freak_id'], ['meteorological.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_recommendation')
    op.drop_table('recommendation')
    op.drop_table('users')
    op.drop_table('meteorological')
    op.drop_table('alerts')
    # ### end Alembic commands ###
